### ISSUE TITLE
Newlines are vaporated on Markdown preview.

### ISSUE THREAD

**Issue by Kjwon15** [forkhubs/android#518]
When I write an issue I got this problem.
I wrote this:
```
\```
some line



some line
\```
```
but preview shows me like this:
```
some line some line
```
It looks fine on web page. but it merged into single line on Android app.

**Comment by EzraBrooks** [comment]
@BetaBugish, it's not so much a duplicate as it is a more general issue. #494 only refers to the README - one of many cases in which Markdown rendering could be done incorrectly.

cc @fadils This is definitely an important bug - maybe close #494 and reference discussion to this thread? I'll poke around in the code to see what's causing it this week.

**Comment by fadils** [comment]
@EzraBrooks sure. I already closed #494.
Will wait for your PR, then. =)

**Comment by EzraBrooks** [comment]
@fadils it seems to be that the way Markdown is rendered in the app is by requesting the GitHub servers to convert it to HTML so the app can display it with WebView. Would rebuilding that to be converted to XML locally for rendering as an Android layout be the best course of action? While that would mean we could fine-tune the display of Markdown files to be density-independent, it would also mean the app would have to be separately updated if the GitHub web interface's implementation of Markdown is changed.

**Comment by fadils** [comment]
@EzraBrooks we should explore into using something like https://github.com/Uncodin/bypass to render our markdown.

It looks like it's a good alternative.

What do you think?

**Comment by EzraBrooks** [comment]
@fadils I would say that we shouldn't import yet another dependency into the project just for rendering Markdown. Plus, according to the [GFM help page](https://help.github.com/articles/github-flavored-markdown/) GitHub isn't using standard Markdown, so we'd need to extend the functionality of Bypass to process GitHub Flavoured Markdown on top of the standard.  
  
Also, if you ask me, Bypass having multiple dependencies outside of its own project scope is a bit ridiculous for the amount of work it actually does.

**Comment by fadils** [comment]
@EzraBrooks it is pretty overkill. =(

**Comment by fadils** [comment]
I'm sorry I think I'm lost in the thick of other things.. =(

Is this happening with the current build? Or with the version from Play store?

@Kjwon15 @EzraBrooks

**Comment by EzraBrooks** [comment]
@fadils I was trying to replicate the bug on the Play Store version, but couldn't even get to *any* issues. I would test in the current build, but I don't have a computer to build with right now, as my laptop is off for repairs.

**Comment by Meisolsson** [comment]
You can test it on ForkHub, it's almost as outdated as the Play Store verison

**Comment by EzraBrooks** [comment]
@Meisolsson @fadils When I tried to replicate the error in ForkHub, the Markdown wasn't even parsed properly - it didn't even seem to try to parse it. All the special characters were displayed as-is instead of changing the formatting.

**Comment by EzraBrooks** [comment]
@fadils @Meisolsson I can confirm that code blocks aren't rendered properly in the newest development version of the app - although, that's better than the old version, as that doesn't seem to work at all.

**Comment by EzraBrooks** [comment]
From what I've seen exploring the giant spidery mass of code that affects this issue, the app does Markdown rendering in a bit of a roundabout way. We're using Eclipse's classes for interaction with GitHub (which is kind of silly - since it's the official app, it really should be using in-house implementations of that sort of thing) to pull Markdown pre-converted into HTML from the API. It then crams HTML into a TextView, which is even weirder and is bound to cause some formatting errors. We should either pull down pure Markdown and parse it locally or switch to using a WebView with the remotely-rendered files. Regardless of which method we take, we should probably fork Eclipse's GitHub Mylyn connector package or rewrite the API interactions of the app that currently use Eclipse's implementation from the ground up. Better control over development that way, and those Mylyn connectors were never intended to be used for this purpose. I would prefer we switch to rendering Markdown locally into XML compatible with Android's layout system, but using HTML like we are already is an option.

**Comment by TheLonelyGhost** [comment]
The problem with rendering Markdown locally is that it might not follow the added sugar for Github-flavored markdown. Do we want to have dual tracks for updating the markdown parser like that?

By using a Github endpoint to render markdown as HTML, we can just use a browser to view it, though webviews before using the chrome rendering engine were admittedly bad at web standards.

**Comment by EzraBrooks** [comment]
Upon further research into the code, it looks like our two best courses for fixing Markdown are either to reimplement everything that needs Markdown rendering into WebView instead of TextView - or to fix our implementation of TextView, as it uses a few deprecated methods. I'm not sure TextView supports all the styling we use in GFM, though, so I think we should switch to WebView.

**Comment by hzsweers** [comment]
Bypass is very lightweight, and has gained some significant improvements recently with the help of the Trello android team. That said, it doesn't support GFM. I'm not sure what the best solution for this would be, other than maybe viewing the README in a webview. We should give bypass a try though. If all we lose is syntax highlighting, I think it would be worth it.

**Comment by hzsweers** [comment]
Continued more genericallyin #790
