### ISSUE TITLE
Update to the new /authorizations API

### ISSUE THREAD

**Issue by ptoomey3** [forkhubs/android#582]
The authorizations API will no longer return `token` as of sometime next year (likely around March). You can read more on the [developer blog](https://developer.github.com/changes/2014-12-08-removing-authorizations-token/). The login logic will need to be updated to use something more like https://developer.github.com/v3/oauth_authorizations/#get-or-create-an-authorization-for-a-specific-app-and-fingerprint.

**Comment by Meisolsson** [comment]
Any updates on this, what's the plan?

**Comment by EzraBrooks** [comment]
I say we rip out the EGit classes we use and rewrite them one-by-one for API interaction. A large amount of my programming experience actually lies in dealing with JSON APIs (mainly in Python and JavaScript, but I'm sure I can handle it in Java). As Kevin said, the Java API hasn't been updated in a long time. Maybe even work on the new version in a separate repository so others can use our Java wrapper in their projects? This would be a major undertaking because it would mean rewriting a large amount of the app's code, but it would be worth it in the end (in my opinion) because we could document everything and know exactly how the code works to fix all the strange issues that manifest from the EGit classes.

**Comment by fadils** [comment]
@Meisolsson Sorry for the late reply. I'm still not feeling well lately. Last contact with @jonanp, he's pretty hectic too.
So, if you can give us a hand, that would be great.

Otherwise, I'm planning on doing it once I feel better.

**Comment by Meisolsson** [comment]
I'm on vacation but I'll try to create a base that we can build on when I get back.
On Feb 14, 2015 7:23 AM, Fadil Sutomo <notifications@github.com> wrote:@Meisolsson Sorry for the late reply. I'm still not feeling well lately. Last contact with @jonanp, he's pretty hectic too.
So, if you can give us a hand, that would be great.

Otherwise, I'm planning on doing it once I feel better.

**Comment by Meisolsson** [comment]
Or if @EzraBrooks wants to start he could.

**Comment by fadils** [comment]
@Meisolsson I'm currently fixing #376. I'm including retrofit as part of the solution, so I guess we can use it as a base for this issue.
I'm gonna PR in 1-2 hours. Else, next morning.

**Comment by Meisolsson** [comment]
Sounds good!

**Comment by hzsweers** [comment]
I'll try to tackle this this weekend

**Comment by Meisolsson** [comment]
Not to sound annoying but we need to tackle this or look into #792, mostly cause this needs to be fixed before release.

**Comment by hzsweers** [comment]
Yeah, I'm still planning to work on this, just currently on vacation. I
won't have time until probably early June either due to IO and interns
arriving as soon as I get back. PRs welcome :)

**Comment by Leaking** [comment]
The API is updated now,And the previous API can't get token.

**Comment by Meisolsson** [comment]
This is fixed so I'll close it
