### ISSUE TITLE
What's the status of this?

### ISSUE THREAD

**Issue by hzsweers** [forkhubs/android#765]
Looks like this was moved to forkhubs. Who is in charge/organizing and what's the plan moving forward?

**Comment by Vorgone** [comment]
I think @jonan but I'm not sure.

**Comment by fadils** [comment]
@hzsweers we're in the process of releasing our first version. Probably something 0.1.0. That's first.
Then, we gradually build up from there. Tackling issues down (which has a lot, btw).
So, yes. Your contribution is very much welcome. And if you want to be a contributor, let me know so that I can send you an invitation.

We're also trying to come up with a reasonable organization name too.

**Comment by larsgrefer** [comment]
I'd like to become a contributor too.
So I can help merging all the queued pull requests and reviewing all the open issues

**Comment by larsgrefer** [comment]
In order to answer @hzsweers ´s first question: The current owners of this repository are (at least) @fadils, @jonan and @kevinsawicki

**Comment by hzsweers** [comment]
@fadils I'd be happy to help contribute. I don't know how much time I'll have for actual development, but at the very least I can help triage issues and review pull requests.

**Comment by larsgrefer** [comment]
@hzsweers Then @fadils should send the promised invitation(s). Please?
