### ISSUE TITLE
PlayStore entries and app updates

### ISSUE THREAD

**Issue by larsgrefer** [forkhubs/android#772]
I´d like to use this issue to discuss what could, should and will happen with the PlayStore Entries like mentioned in #736 and #763.

The decision is: Updating the old app or releasing a new one.

To update the old app we'd need access to the signing-keystore and to the google play developer console. This option would be the easiest for the users, but we need the permission from GitHub (as discussed in #771).

When releasing a new app, we would have to find a new name for the developer/pubisher and maybe even a new name for the whole app (for the last point see #771).

Even if we don´t get access to the keystore and playStore developer console and are forced to use the second option it'd be great to publish one last update for the old app replacing the actual app with a hint about the new app

**Comment by kevinsawicki** [comment]
> To update the old app we'd need access to the signing-keystore and to the google play developer console

Yeah, I don't think giving out access to the keystore is something that can happen.

**Comment by larsgrefer** [comment]
In this case we're forced to publish a new app under a new name (with a new keystore).

@kevinsawicki What's your opinion on my last suggestion? One last update for the users of the old app which just contains a single activity with a hint like "This app is not longer maintained. The new Version can be found here: <play-store-link>"

**Comment by kevinsawicki** [comment]
> One last update for the users of the old app which just contains a single activity with a hint like "This app is not longer maintained. The new Version can be found here: "

Yeah, I think this is a good idea and something worth doing :+1:

**Comment by larsgrefer** [comment]
Thanks @kevinsawicki 
But we should wait with this until the first version of the new app is published

**Comment by larsgrefer** [comment]
Should i provide this 'dummy' app?
in an extra branch? or extra repository?

**Comment by kevinsawicki** [comment]
> But we should wait with this until the first version of the new app is published

Yeah, I think this makes sense.

> Should i provide this 'dummy' app?

Maybe just as dialog in the existing app that shows at launch?

**Comment by larsgrefer** [comment]
This would be possible, but it in this case the new app has to be based on the 1 year old 1.9.0 release

Furthermore you have removed the app from google play which means in my opinion that you don't want the old app to be used anymore and 'just a dialog' wouldn't make the app unusable

**Comment by SecUpwN** [comment]
Since the discussion in this Issue if flowing beautifully, let me add two questions:

1. What happened to the old app? I have seen that @fadils forked it and basically saved its life.
2. Would you please add [this link](https://play.google.com/store/apps/details?id=com.github.mobile) to your app description just like [here](https://github.com/fadils/android)?

**Comment by fadils** [comment]
I'm finalizing everything to upload the app to the appstore.
It's still based on 1.9.0.

**Comment by M-Zuber** [comment]
Just to understand, the version that @fadils is releasing is going to be the unofficial successor to the official app? or just a redirect to somewhere else?

**Comment by StefMa** [comment]
Come on guys. Update your readme on what you are working and what if planned. Write down why it isn't 'official' from github anymore and closed the one hundred issues about that subject...

**Comment by hzsweers** [comment]
@StefMa we're sifting through outstanding pull requests and issues. We have full time jobs and it's not something we should rush through.

**Comment by larsgrefer** [comment]
@StefMa When the planning (what this issue is made for) is finished, we will update the README accordingly.
But for now, we are waiting for @fadils answer to @M-Zuber's question

**Comment by hzsweers** [comment]
Been talking with @fadils about this privately

My proposal for a general roadmap (with **no** ETAs) though is this:

1. We don't rush something out the door. We need to get to a stable base, and then maybe shoot for the initial release of the public project as a 0.1.0 release. From a stability standpoint, we should try to get our open issue count back down to 0, and then move from there.

2. Formalized structure for new app. Organization, releases, new app name, etc. My suggestions for the hat are:
  * **App Name:** Octo
  * **Play Store Publisher:** Forkhubs

3. Get everyone on the same page. There's one or two forks out there that are maintaining parallel development, and this just fragments the process. People don't know what to contribute to. Now that we have a formal successor, we should get everyone onboard with this so that there's no confusion about where someone should contribute to. We should also start bringing in the improvements/fixes from those forks back to this project. We should also stop referring people to them, either in pull requests/issues or as an alternative, again because it just fragments the process. What's more annoying is one or two of these forks I've seen on the play store claim credit for changes they didn't make. (@jonan you're not one of them, just to be clear :smiley:)

4. We have a single updated version of the original app for one final release, that just shows a dialog saying the project has migrated to this and include a link to the new play store link. We would launch this at the same time as the new one. @kevinsawicki please let us know what you think of this.

5. Proper crash reporting. Not sure what's in place or accessible right now, but Bugsnag is great and free for open source projects (as long as we give them a public shoutout in the README or somewhere). This way collaborators on the project can have access to this and triage crashers from it.

6. Finish the visual refresh. We started this in December, and have come a long way as far as getting a nice material design look. This plus stability can be the main feature point of a 2.0 release. There's still a few outstanding areas we can improve here:
  * List items UI (maybe borrow a little from u2020's new look)
  * Material dialogs (I see it's added, but I don't see them in the actual app yet). Preferably using the new AppCompat versions.
  * Text input fields. They're currently very boxy. I get that this was originally to match the Github website UI, but I think this project should take advantage of its new flexibility and move in a more material and conventional android direction.

Getting a stable release out the door would be a massive first step. After that we can start to work on new features. For now I think stability, the UI refresh, and migration should be the major platforms for the first release. We can consider doing a beta on the play store first as well.

**Comment by larsgrefer** [comment]
@hzsweers For number 4 look at this comment by @kevinsawicki: https://github.com/forkhubs/android/issues/772#issuecomment-93604590

**Comment by hzsweers** [comment]
Oops, must've missed that. Good to know

**Comment by fadils** [comment]
Agree to whatever @hzsweers mentions above..

**Comment by M-Zuber** [comment]
Thanks for the update. Sounds great. I am very much so looking forwards ti going back to a native app.

**Comment by SecUpwN** [comment]
@hzsweers, thank you for publishing the master plan, it feels good to eyeball all this and learn stuff for my own projects. General question directed to you: How come you chose [Bugsnag](https://bugsnag.com/) instead of [CoverityScan](https://scan.coverity.com/) or [Fabric](https://get.fabric.io/)? Would someone, possibly even @fadils, be so friendly to clarify what happened to the original GitHub Anddroid app? How come the whole project even has to move? I don't get the story..

**Comment by hzsweers** [comment]
GitHub has moved the project to a new home, and will no longer be maintaining it. Instead, it will now be a community-developed project. We're currently working on preparing it for an initial stable release (that is, not much different than the last official store app functionally. A UI refresh, squashed bugs since, and migration from the original app). After that, we will begin new feature work.

I like Bugsnag because it's simple and has a no-BS approach to error tracking. Both Fabric and CoverityScan's websites make me want to gauge my eyes out. I've used Bugsnag, Crashlytics, and HockeyApp, and found Bugsnag to be the cleanest/most practical solution by far.

I checked them out after a glowing review from Jake Wharton from Square (he/they use them as well). Here's a link to that for a more in-depth look at Bugsnag: http://www.reddit.com/r/androiddev/comments/2sw11m/anyone_used_bugsnag/

**Comment by SecUpwN** [comment]
Thanks for sharing the background, @hzsweers! Will discuss using [Bugsnag](https://bugsnag.com/) with my team now.

**Comment by rsvp** [comment]
@hzsweers said, "Instead, it will now be a community-developed project." So is there a public URL for this?

Is "ForkHub for GitHub" by Jon Ander Peñalba the so-called community version?
https://play.google.com/store/apps/details?id=jp.forkhub

Please kindly clarify which app at the Google Play Store is most legitimate, since GitHub removed the official version. Thanks.

**Comment by hzsweers** [comment]
No. ForkHub is not the community version. It's a fork maintained by @jonan that was originally started due to the lack of maintenance here. It is my hope that he will stop maintaining it and referring issues here to that now that this is ramping up again, and help us focus on this project again. For better or worse, the organization name chosen when GitHub relinquished this project is just very similar. I can definitely understand the confusion.

There is no "legitimate" app on the play store by any legal standards. This app will be no different. The app in *this* repo is *not* on the play store, yet. It will be once we release it. We are focusing on getting it to a solid foundation, finishing the UI refresh we started, and clearing/triaging the outstanding issues and PRs that have accumulated. There is no time table for this, it will be done when it's done.

**Comment by alorma** [comment]
I don't think there is a "legitim" app.

Apps ending in "hub" *are* forks:

ForksHub
ModernHub

And other *aren't*:

GitSkarios
OctoDroid

Please, don't use the term "legit" since GitHub removed their own app

That's the game of thrones... sorry, apps

**Comment by hzsweers** [comment]
That's coincidence, but not a formal naming convention.

So yes, as I already said

> There is no "legitimate" app on the play store by any legal standards. This app will be no different.

**Comment by alorma** [comment]
Yes i know it's coincidence, it's just all ".hub" apps are forks :)

**Comment by SecUpwN** [comment]
>Please, don't use the term "legit" since GitHub removed their own app

I still don't get why @GitHub removed **their own app**! It just doesn't want to stick in my mind...

**Comment by SecUpwN** [comment]
I'd actaully enjoy if @GitHub or @forkhubs would **ditch Google** like our [AIMSICD](https://secupwn.github.io/Android-IMSI-Catcher-Detector/) does [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/FAQ#q-why-wont-you-upload-your-app-to-the-google-play-store). :+1:

**Comment by hzsweers** [comment]
That's not happening.

**Comment by SecUpwN** [comment]
>That's not happening.

Then at the very least, please also officially distribute your app via [![F-Droid](https://f-droid.org/wp-content/uploads/2014/04/cropped-header_resp1.png)](https://f-droid.org/)

**Comment by hzsweers** [comment]
Why? People can just build from source or download APKs from the releases
section when we start releasing.

**Comment by SecUpwN** [comment]
>Why? People can just build from source or download APKs from the releases section when we start releasing.

I like that you'll provide the direct download of the APK in your releases. However, some people may find it a good idea being automatically notified when an update is available. I see no reason to avoid F-Droid.

**Comment by hzsweers** [comment]
I do, simply because F-Droid's cult following constantly nagging developers to upload apps to another distribution system rubs me the wrong way, and I'm not interested in condoning it.

**Comment by fadils** [comment]
-closely paying attention-
:smile:

**Comment by SecUpwN** [comment]
>-closely paying attention-

Waiting for the bitch-fight? ;-) No, I respect @hzsweers choice, but could also offer to set it up for you.

**Comment by wp9015362** [comment]
Hello,

> @hzsweers wrote in https://github.com/forkhubs/android/issues/772#issuecomment-97620340:
> 
> No. ForkHub is not the community version. It's a fork maintained by @jonan that was originally started due to the lack of maintenance here. It is my hope that he will stop maintaining it and referring issues here to that now that this is ramping up again, and help us focus on this project again.

I read the following comment from @jonan : 

> @jonan wrote in https://github.com/jonan/ForkHub/issues/15#issuecomment-99229049:
> 
> There is no longer an official app, GitHub has removed it from the Play Store and moved the repository to https://github.com/forkhubs/android. That repo and this one are improving the old app taking different paths.

Does that mean that you are not working together and that there will be two different apps now?

Regards

**Comment by hzsweers** [comment]
I guess. I called on forkers an an earlier comment here to focus on this repo now that it's a public project, but never got a response from him specifically. This repo is the original repo though, and for all intents and purposes will be the spiritual successor to the original.

**Comment by SecUpwN** [comment]
>I called on forkers an an earlier comment here to focus on this repo now that it's a public project, but never got a response from him specifically.

Uncool. It would be much better if @jonan was so kind so send an answer to @hzsweers, so that you guys really do not move apart, but make a unifioed effort to craft **one awesome app**. Please try again!

**Comment by hzsweers** [comment]
This thread has become sidetracked, so I'm closing it. We have a plan, and will be proceeding with it. Please see the README for further updates.

**Comment by alorma** [comment]
I recommend you to lock the issue too, if not people will comments and
reopen it

**Comment by hzsweers** [comment]
Good point, done.
